find . -type f -name '*.bcf' -delete
find . -type f -name '*.out' -delete
find . -type f -name '*.blg' -delete
find . -type f -name '*.bbl' -delete
find . -type f -name '*.aux' -delete
find . -type f -name '*.fdb_latexmk' -delete
find . -type f -name '*.fls' -delete
find . -type f -name '*.log' -delete
find . -type f -name '*.lof' -delete
find . -type f -name '*.lot' -delete
find . -type f -name '*.toc' -delete
find . -type f -name '*.run.xml' -delete
find . -type f -name '*.synctex.gz' -delete
find . -type f -name '*.pdf' -delete
find . -type f -name '*.glg' -delete
find . -type f -name '*.glo' -delete
find . -type f -name '*.gls' -delete
find . -type f -name '*.glsdefs' -delete
find . -type f -name '*.ist' -delete
